name: Deploy to EC2
on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - run: |
          chmod +x gradlew
          ./gradlew build test

      - uses: actions/upload-artifact@v4
        with:
          name: gatewayservice-jar
          path: build/libs/*.jar

      - uses: actions/download-artifact@v4
        with:
          name: gatewayservice-jar
          path: ./

      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          source: "./*.jar"
          target: "/opt/tata/gatewayservice/"

      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            cd /opt/tata/gatewayservice
            JAR_FILE=$(ls gatewayservice-v*.jar | sort -V | tail -n 1)
            [ -f Dockerfile ] && [ -n "$JAR_FILE" ] || exit 1
            
            cp "$JAR_FILE" gatewayservice.jar
            
            docker stop gatewayservice 2>/dev/null || true
            docker rm gatewayservice 2>/dev/null || true
            
            docker build -t gatewayservice . 
            docker run -d --name gatewayservice -p 8080:8080 gatewayservice
            
            docker ps | grep gatewayservice || { 
                docker ps -a | grep gatewayservice
                docker logs gatewayservice
                exit 1
            }
